publications:
    - name: prod
      suffix: ""
      server: sftp://uploader@package-upload.edgedb.net:22/

targets:
    linux:
        - name: linuxmusl-x86_64
          arch: x86_64
          platform: linux
          platform_version: x86_64
          platform_libc: musl
          family: generic
          runs_on: [package-builder, self-hosted, linux, x64]
        - name: linuxmusl-aarch64
          arch: aarch64
          platform: linux
          platform_version: aarch64
          platform_libc: musl
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]

    macos: []
